apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: book-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/MiltonRPG/proyecto-cicd-keepcoding.git'
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
