apiVersion: v1
kind: Service
metadata:
  name: argocd-nodeport
  namespace: argo
spec:
  type: NodePort
  selector:
    app: argo-server
  ports:
    - protocol: TCP
      port: 2746
      targetPort: 2746
      nodePort: 30080  # Puedes cambiar este puerto si ya está en uso
