apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: book-app-hpa
  namespace: book-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: book-app  # Asegúrate de que este nombre coincida con el de tu deployment.yaml
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Escalará cuando el uso de CPU supere el 70%
