name: CI Pipeline

on:
  push:
    branches:
      - develop
      - master

permissions:
  contents: write  # Permisos de escritura para contenidos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd book-app
          npm install

      - name: Run lint
        run: |
          cd book-app
          npm install  # Asegura que las dependencias estén instaladas
          chmod +x ./node_modules/.bin/eslint  # Configura permisos de ejecución
          ./node_modules/.bin/eslint .

      - name: Run tests with coverage
        run: |
          cd book-app
          chmod +x ./node_modules/.bin/jest  # Configura permisos de ejecución para Jest
          ./node_modules/.bin/jest --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: book-app/coverage

      - name: Snyk Security Scan
        run: |
          cd book-app
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test

      - name: Build Docker image
        run: docker build -t book-app:latest .

      - name: Push Docker image
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag book-app:latest miltonrpg/book-app:latest
          docker push miltonrpg/book-app:latest
        #Comentario

